`timescale 1ns / 1ps
module Extender(
input [31:0] X_in,
input ZE_SE,
output reg [31:0] X_out
    );

/*  DO NOT EDIT THIS FILE   */


localparam Ext_delay= 0.5; //500 ps
always @(X_in or ZE_SE)
begin
	if (ZE_SE=== 1'b0)  X_out <=#Ext_delay {16'b0000000000000000,X_in[15:0]};
	else if (ZE_SE=== 1'b1) X_out <=#Ext_delay  {16'b1111111111111111*X_in[15],X_in[15:0]};
end


endmodule
