`timescale 1ns / 1ps
module Register4(
input [3:0] Data_in,
output reg[3:0] Data_out,
input Wr, //Sync.
input Reset, //Async.
input Clk
    );


/*  DO NOT EDIT THIS FILE   */

localparam Reg_delay= 2; //2 ns

always @(Reset)
begin
	if (Reset)  Data_out<=#Reg_delay 0;
end
always @(posedge Clk)
begin
	if (Wr)
	begin
		Data_out <=#Reg_delay Data_in; 
	end
end

endmodule
