`timescale 1ns / 1ps
module Switch32(
input [31:0] A_in,
output reg [31:0] A_out,
output reg [31:0] B_out,
input [31:0] C_in,
input Sel
    );
	 
/*  DO NOT EDIT THIS FILE   */	 
	 
localparam Switch_delay= 0.5; //500 ps	 
always@(A_in or C_in or Sel)
begin
	if (Sel===1'b0) 
	begin
		B_out <=#Switch_delay A_in;
	end
	else if (Sel===1'b1)  A_out <=#Switch_delay C_in;
end
    
endmodule
